service: homeautomation-lamda-rest-api

frameworkVersion: "3"

#https://www.serverless.com/plugins/serverless-dotenv-plugin
useDotenv: true
provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 2048
  stage: staging
  timeout: 15
  region: ap-south-1

functions:
  restApiHandler:
    handler: handler.restApiHandler
    events:
      - http: ANY /{proxy+}
      - http: ANY /
    environment:
      SECRET_KEY: ${env:SECRET_KEY}
